from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from sqlalchemy import or_

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.db.session import SessionLocal
from app.modules.appointment.appointment import Appointment
from app.modules.identity.service import seed_default_admin
from app.modules.identity.user import User


PROTECTED_ADMIN_USERNAMES = {"madao", "madao1", "madao2", "madao3", "madao4"}
SHADOW_ADMIN_PATTERN = re.compile(r"^madao[1-4]_\d{10}$")
TEST_APPOINTMENT_NAMES = {"Smoke Visitor", "Regression Visitor"}
TEST_APPOINTMENT_REASONS = {"Visitor smoke test", "Smoke Test Flow", "Regression Test Flow"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Clean local demo data generated by smoke/regression runs.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete matched records. Without this flag the script only prints a dry run summary.",
    )
    parser.add_argument(
        "--skip-users",
        action="store_true",
        help="Do not remove shadow admin accounts.",
    )
    parser.add_argument(
        "--skip-appointments",
        action="store_true",
        help="Do not remove smoke/regression appointments.",
    )
    return parser.parse_args()


def find_shadow_admins(session) -> list[User]:
    users = session.query(User).order_by(User.id.asc()).all()
    return [
        user
        for user in users
        if user.username not in PROTECTED_ADMIN_USERNAMES and SHADOW_ADMIN_PATTERN.fullmatch(user.username or "")
    ]


def find_test_appointments(session) -> list[Appointment]:
    return (
        session.query(Appointment)
        .filter(
            or_(
                Appointment.name.in_(TEST_APPOINTMENT_NAMES),
                Appointment.reason.in_(TEST_APPOINTMENT_REASONS),
            )
        )
        .order_by(Appointment.id.asc())
        .all()
    )


def main() -> None:
    args = parse_args()
    session = SessionLocal()
    try:
        seed_default_admin(session)
        shadow_admins = [] if args.skip_users else find_shadow_admins(session)
        test_appointments = [] if args.skip_appointments else find_test_appointments(session)

        print("Cleanup demo data summary")
        print(f"- shadow admin users: {len(shadow_admins)}")
        for user in shadow_admins:
            print(f"  - user#{user.id}: {user.username} ({user.role})")
        print(f"- smoke/regression appointments: {len(test_appointments)}")
        for record in test_appointments:
            print(
                f"  - appointment#{record.id}: {record.name} / {record.phone} / {record.status} / {record.reason}"
            )

        if not args.apply:
            print("")
            print("Dry run only. Re-run with --apply to delete the matched records.")
            return

        for record in test_appointments:
            session.delete(record)
        for user in shadow_admins:
            session.delete(user)

        session.commit()
        print("")
        print("Cleanup applied successfully.")
        print(f"- deleted appointments: {len(test_appointments)}")
        print(f"- deleted shadow admin users: {len(shadow_admins)}")
    finally:
        session.close()


if __name__ == "__main__":
    main()
