(function registerWebDomElements(global) {
  function createWebDomElements(byId) {
    const visitorElements = {
      healthNode: byId("ping-result"),
      pingButton: byId("ping-button"),
      applyForm: byId("apply-form"),
      applyResultNode: byId("apply-result"),
      ticketCard: byId("ticket-card"),
      applicationIdNode: byId("application-id"),
      accessCodeNode: byId("access-code"),
      queryForm: byId("query-form"),
      queryCard: byId("query-card"),
      queryResultNode: byId("query-result"),
      queryNameNode: byId("query-name"),
      queryStatusNode: byId("query-status"),
      queryTimeNode: byId("query-time"),
      queryTargetNode: byId("query-target"),
      queryRemarkNode: byId("query-remark"),
      passResultNode: byId("pass-result"),
      passStatusBadge: byId("pass-status-badge"),
      visitorPassCard: byId("visitor-pass-card"),
      passApplicationIdNode: byId("pass-application-id"),
      passAccessCodeNode: byId("pass-access-code"),
      passNameNode: byId("pass-name"),
      passPhoneNode: byId("pass-phone"),
      passTargetNode: byId("pass-target"),
      passTimeNode: byId("pass-time"),
      passRemarkNode: byId("pass-remark"),
      passApprovedByNode: byId("pass-approved-by"),
      passApprovedAtNode: byId("pass-approved-at"),
      passCheckedInAtNode: byId("pass-checked-in-at"),
      passPayloadNode: byId("pass-payload"),
      copyPassPayloadButton: byId("copy-pass-payload"),
      passQrNoteNode: byId("pass-qr-note"),
      passQrWrapNode: byId("pass-qr-wrap"),
      passQrImageNode: byId("pass-qr-image"),
      openPassQrLink: byId("open-pass-qr"),
    };

    const adminElements = {
      adminSessionCard: byId("admin-session-card"),
      adminSessionUserNode: byId("admin-session-user"),
      adminSessionRoleNode: byId("admin-session-role"),
      adminAvatarPreview: byId("admin-avatar-preview"),
      adminAvatarImageNode: byId("admin-avatar-image"),
      adminAvatarInitialNode: byId("admin-avatar-initial"),
      adminAvatarInput: byId("admin-avatar-file"),
      logoutButton: byId("logout-button"),
      refreshAccountButton: byId("refresh-account-button"),
      accountCard: byId("account-card"),
      accountResultNode: byId("account-result"),
      accountUsernameNode: byId("account-username"),
      accountStatusNode: byId("account-status"),
      accountCreatedAtNode: byId("account-created-at"),
      passwordForm: byId("password-form"),
      passwordResultNode: byId("password-result"),
      refreshUsersButton: byId("refresh-users-button"),
      usersResultNode: byId("users-result"),
      usersEmptyNode: byId("users-empty"),
      usersListNode: byId("users-list"),
      userManagementPanel: byId("user-management-panel"),
      userManagementTipNode: byId("user-management-tip"),
      createUserForm: byId("create-user-form"),
      createUserResultNode: byId("create-user-result"),
      editUserPanel: byId("edit-user-panel"),
      editUserForm: byId("edit-user-form"),
      editUserIdInput: byId("edit-user-id"),
      editUserStatusNode: byId("edit-user-status"),
      editUserResultNode: byId("edit-user-result"),
      cancelUserEditButton: byId("cancel-user-edit-button"),
      refreshAdminButton: byId("refresh-admin-button"),
      adminResultNode: byId("admin-result"),
      refreshStatsButton: byId("refresh-stats-button"),
      statsResultNode: byId("stats-result"),
      statsTotalNode: byId("stats-total"),
      statsPendingNode: byId("stats-pending"),
      statsApprovedNode: byId("stats-approved"),
      statsRejectedNode: byId("stats-rejected"),
      statsExpiredNode: byId("stats-expired"),
      statsCheckedInNode: byId("stats-checked-in"),
      refreshOverviewButton: byId("refresh-overview-button"),
      overviewResultNode: byId("overview-result"),
      todayCreatedNode: byId("today-created"),
      todayPendingNode: byId("today-pending"),
      todayApprovedNode: byId("today-approved"),
      todayRejectedNode: byId("today-rejected"),
      todayCheckedInNode: byId("today-checked-in"),
      todayExpiredNode: byId("today-expired"),
      activityEmptyNode: byId("activity-empty"),
      activityListNode: byId("activity-list"),
      expireStaleButton: byId("expire-stale-button"),
      expireStaleResultNode: byId("expire-stale-result"),
      adminAuthTipNode: byId("admin-auth-tip"),
      adminEmptyNode: byId("admin-empty"),
      pendingListNode: byId("pending-list"),
      checkInForm: byId("check-in-form"),
      expireForm: byId("expire-form"),
      operationResultNode: byId("operation-result"),
      startScanButton: byId("start-scan-button"),
      scanCheckInButton: byId("scan-check-in-button"),
      stopScanButton: byId("stop-scan-button"),
      inspectScanButton: byId("inspect-scan-button"),
      scannerSupportNode: byId("scanner-support"),
      scannerPreviewNode: byId("scanner-preview"),
      scannerVideoNode: byId("scanner-video"),
      scannerResultNode: byId("scanner-result"),
      scanRecordCard: byId("scan-record-card"),
      scanRecordIdNode: byId("scan-record-id"),
      scanRecordNameNode: byId("scan-record-name"),
      scanRecordPhoneNode: byId("scan-record-phone"),
      scanRecordTargetNode: byId("scan-record-target"),
      scanRecordTimeNode: byId("scan-record-time"),
      scanRecordStatusNode: byId("scan-record-status"),
      scanRecordRemarkNode: byId("scan-record-remark"),
      scanRecordCodeNode: byId("scan-record-code"),
      scanConfirmModal: byId("scan-confirm-modal"),
      closeConfirmModalButton: byId("close-confirm-modal"),
      confirmCheckInButton: byId("confirm-check-in-button"),
      confirmModalTipNode: byId("confirm-modal-tip"),
      confirmRecordIdNode: byId("confirm-record-id"),
      confirmRecordNameNode: byId("confirm-record-name"),
      confirmRecordPhoneNode: byId("confirm-record-phone"),
      confirmRecordTargetNode: byId("confirm-record-target"),
      confirmRecordTimeNode: byId("confirm-record-time"),
      confirmRecordStatusNode: byId("confirm-record-status"),
      confirmRecordRemarkNode: byId("confirm-record-remark"),
      confirmRecordCodeNode: byId("confirm-record-code"),
      historyForm: byId("history-form"),
      refreshHistoryButton: byId("refresh-history-button"),
      historyResultNode: byId("history-result"),
      historyEmptyNode: byId("history-empty"),
      historyListNode: byId("history-list"),
      historyPageInfoNode: byId("history-page-info"),
      historyPrevButton: byId("history-prev-button"),
      historyNextButton: byId("history-next-button"),
      clearHistoryFiltersButton: byId("clear-history-filters-button"),
      logsForm: byId("logs-form"),
      refreshLogsButton: byId("refresh-logs-button"),
      logsResultNode: byId("logs-result"),
      logsEmptyNode: byId("logs-empty"),
      logsListNode: byId("logs-list"),
      logsPageInfoNode: byId("logs-page-info"),
      loadMoreLogsButton: byId("load-more-logs-button"),
    };

    return {
      ...visitorElements,
      ...adminElements,
    };
  }

  global.createWebDomElements = createWebDomElements;
})(window);
